In [91]:
import pandas as pd
train_df = pd.read_csv('../dataset/train.csv', usecols=['readme', 'description'])
val_df = pd.read_csv('../dataset/validation.csv', usecols=['readme', 'description'])

In [92]:
# func
def prompts(df):
    prompts = []
    for sample in df['readme']:
        prompts.append(f"""### Instruction:
            Summarize the following README contents with LESS THAN 50 words. Your answer should be based on the provided README contents only.
            ### README contents:
            {sample}
            ### Summary:
            """)
    return prompts

# main func
train_prompts_df = pd.DataFrame(data=prompts(train_df), columns=['prompt'])
val_prompts_df = pd.DataFrame(data=prompts(val_df), columns=['prompt'])

for prompt in train_prompts_df:
    train_prompts_df.loc[-1] = [prompt]
    train_prompts_df.index += 1
train_prompts_df.index -= 1

for prompt in val_prompts_df:
    val_prompts_df.loc[-1] = [prompt]
    val_prompts_df.index += 1
val_prompts_df.index -= 1
    
new_train_df = pd.concat([train_df, train_prompts_df], axis=1).dropna()
new_val_df = pd.concat([val_df, val_prompts_df], axis=1).dropna()

In [93]:
new_train_df

,readme,description,prompt
0,JDA (Java Discord API)JDA strives to provide a...,Java wrapper for the popular chat & VOIP servi...,### Instruction:\n Summarize the fo...
1,b'# ArnoldC\n\nProgramming language based on t...,Arnold Schwarzenegger based programming language,### Instruction:\n Summarize the fo...
2,[<marko.inline.RawText object at 0x000001592FE...,Multi-user server for Jupyter notebooks,### Instruction:\n Summarize the fo...
3,yowsup For private consultancy feel free to di...,The WhatsApp lib,### Instruction:\n Summarize the fo...
4,English | IntroductionHyperf is an extremely p...,🚀 A coroutine framework that focuses on hypers...,### Instruction:\n Summarize the fo...
...,...,...,...
5826,b'# awesome-business-apps\nAwesome business ap...,"Business build upon open source, support them ...",### Instruction:\n Summarize the fo...
5827,b'CircleImageView\n===============\n\nA fast c...,A circular ImageView for Android,### Instruction:\n Summarize the fo...
5828,Advanced NLP with spaCy: A free online courseT...,👩‍🏫 Advanced NLP with spaCy: A free online course,### Instruction:\n Summarize the fo...
5829,PyTorch Template ProjectPyTorch deep learning ...,PyTorch deep learning projects made easy.,### Instruction:\n Summarize the fo...
5830,⚡️ ContributeCaption is completely open-source...,"Get Caption, start watching.",### Instruction:\n Summarize the fo...

In [94]:
new_val_df

,readme,description,prompt
0,This library allows you to quickly and easily ...,"The Official Twilio SendGrid Led, Community Dr...",### Instruction:\n Summarize the fo...
1,Uncle Steve's Big List of Text Analytics and N...,Resources for learning about Text Mining and N...,### Instruction:\n Summarize the fo...
2,b'\n\n\n\n## Notice: Unmaintained\nThis repo i...,A Markdown parser for javascript,### Instruction:\n Summarize the fo...
3,Yar - Yet Another RPC framework for PHP Light...,"Light, concurrent RPC framework for PHP & C",### Instruction:\n Summarize the fo...
4,b'###### Welcome to follow me on GitHub or Twi...,Ultra Pull to Refresh for Android. Support all...,### Instruction:\n Summarize the fo...
...,...,...,...
829,pip-tools = pip-compile + pip-syncA set of com...,A set of tools to keep your pinned Python depe...,### Instruction:\n Summarize the fo...
830,b'\n\n# Awesome Machine Learning Jupyter Noteb...,A curated list of Machine Learning and Deep Le...,### Instruction:\n Summarize the fo...
831,Frustration: One Year With RReece Goding1 Intr...,An extremely long review of R.,### Instruction:\n Summarize the fo...
832,b'# Apache ECharts\n\n\n \n\n\nApache EChar...,"Apache ECharts is a powerful, interactive char...",### Instruction:\n Summarize the fo...
833,b'# \n\nAn opinionated kickstarter for proje...,A sophisticated build management system for we...,### Instruction:\n Summarize the fo...